// ---------- Book Catalogue ----------
// Data sourced from Open Library (openlibrary.org)
// Cover images via Open Library Covers API: https://covers.openlibrary.org/b/id/{coverId}-M.jpg
// Categories: Fiction, STEM, Kids, History & Biography, Fantasy & Sci-Fi, Self-Help & Wellness, Philosophy & Art

const COVER_BASE = "https://covers.openlibrary.org/b/id/";

const books = [

  // ===== FICTION =====
  {
    id: "f1",
    title: "Shadow Protocol",
    author: "R. K. Lin",
    summary: "A fast-paced mystery with covert ops, shifting alliances, and a case that refuses to stay buried.",
    rating: 4.4,
    category: "Fiction",
    tags: ["mystery", "action", "thriller"],
    location: { floor: 1, aisle: 3, shelf: "C" },
    available: true,
    digital: true,
    coverId: null,
  },
  {
    id: "f2",
    title: "The Midnight Cipher",
    author: "Elena Voss",
    summary: "A codebreaker uncovers a pattern of crimes linked to a decades-old disappearance.",
    rating: 4.2,
    category: "Fiction",
    tags: ["mystery", "suspense", "crime"],
    location: { floor: 1, aisle: 3, shelf: "D" },
    available: true,
    digital: false,
    coverId: null,
  },
  {
    id: "f3",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    summary: "A symbologist and a cryptologist unravel a trail of clues hidden in the works of Leonardo da Vinci, leading to a secret that could shake the foundations of history.",
    rating: 3.9,
    category: "Fiction",
    tags: ["mystery", "thriller", "suspense", "cryptography"],
    location: { floor: 1, aisle: 3, shelf: "A" },
    available: true,
    digital: true,
    coverId: 9255229,
  },
  {
    id: "f4",
    title: "Death on the Nile",
    author: "Agatha Christie",
    summary: "Hercule Poirot investigates a murder aboard a glamorous river steamer cruising the Nile, where everyone on board seems to have a motive.",
    rating: 4.2,
    category: "Fiction",
    tags: ["mystery", "crime", "detective"],
    location: { floor: 1, aisle: 4, shelf: "A" },
    available: false,
    digital: true,
    coverId: 14066646,
  },
  {
    id: "f5",
    title: "The Mysterious Affair at Styles",
    author: "Agatha Christie",
    summary: "In Agatha Christie's first published novel, Hercule Poirot investigates a poisoning at an English country estate, launching one of fiction's greatest detective careers.",
    rating: 4.0,
    category: "Fiction",
    tags: ["mystery", "crime", "detective", "classic"],
    location: { floor: 1, aisle: 4, shelf: "B" },
    available: true,
    digital: true,
    coverId: 13699667,
  },
  {
    id: "f6",
    title: "Whose Body?",
    author: "Dorothy L. Sayers",
    summary: "Lord Peter Wimsey investigates when a body wearing nothing but a pair of pince-nez is discovered in a bathtub, kicking off a delightfully witty mystery.",
    rating: 4.3,
    category: "Fiction",
    tags: ["mystery", "detective", "classic", "crime"],
    location: { floor: 1, aisle: 4, shelf: "C" },
    available: true,
    digital: false,
    coverId: 8311819,
  },
  {
    id: "f7",
    title: "The Innocence of Father Brown",
    author: "G. K. Chesterton",
    summary: "A seemingly unassuming Catholic priest solves crimes through his deep understanding of human nature and evil, proving that wisdom beats brute detection.",
    rating: 4.2,
    category: "Fiction",
    tags: ["mystery", "detective", "classic", "crime"],
    location: { floor: 1, aisle: 4, shelf: "D" },
    available: true,
    digital: true,
    coverId: 94081,
  },
  {
    id: "f8",
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    summary: "A sweeping portrait of Russian society told through the doomed love affair of Anna Karenina and the spiritual journey of the farmer Levin.",
    rating: 4.2,
    category: "Fiction",
    tags: ["classic", "romance", "literary", "russian"],
    location: { floor: 1, aisle: 5, shelf: "A" },
    available: true,
    digital: true,
    coverId: 7740257,
  },
  {
    id: "f9",
    title: "The Plague",
    author: "Albert Camus",
    summary: "When a deadly plague sweeps through the Algerian city of Oran, its citizens must confront isolation, fear, and the search for meaning in the face of collective suffering.",
    rating: 4.1,
    category: "Fiction",
    tags: ["classic", "literary", "philosophical", "french"],
    location: { floor: 1, aisle: 5, shelf: "B" },
    available: false,
    digital: true,
    coverId: 745331,
  },
  {
    id: "f10",
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    summary: "A gripping tale of three brothers entangled in their father's murder, exploring faith, doubt, morality, and the nature of free will.",
    rating: 4.3,
    category: "Fiction",
    tags: ["classic", "literary", "philosophical", "russian"],
    location: { floor: 1, aisle: 5, shelf: "C" },
    available: true,
    digital: false,
    coverId: 11263774,
  },
  {
    id: "f11",
    title: "On the Road",
    author: "Jack Kerouac",
    summary: "The defining novel of the Beat Generation follows Sal Paradise and Dean Moriarty as they crisscross America in search of meaning, freedom, and experience.",
    rating: 3.5,
    category: "Fiction",
    tags: ["classic", "literary", "adventure", "american"],
    location: { floor: 1, aisle: 5, shelf: "D" },
    available: true,
    digital: true,
    coverId: 34655,
  },

  // ===== STEM =====
  {
    id: "st1",
    title: "Deep Work",
    author: "Cal Newport",
    summary: "A practical guide to focused work in a distracted world—perfect for career growth and study habits.",
    rating: 4.6,
    category: "STEM",
    tags: ["career", "productivity", "study", "focus"],
    location: { floor: 2, aisle: 1, shelf: "B" },
    available: true,
    digital: true,
    coverId: 7988607,
  },
  {
    id: "st2",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    summary: "A sweeping account of how Homo sapiens came to dominate the Earth, covering the Cognitive, Agricultural, and Scientific Revolutions that shaped our species.",
    rating: 4.2,
    category: "STEM",
    tags: ["science", "history", "anthropology", "evolution"],
    location: { floor: 2, aisle: 1, shelf: "A" },
    available: true,
    digital: true,
    coverId: 8634250,
  },
  {
    id: "st3",
    title: "Jurassic Park",
    author: "Michael Crichton",
    summary: "A visionary billionaire creates a theme park of cloned dinosaurs on a remote island, but nature proves impossible to control in this thrilling cautionary tale about genetic engineering.",
    rating: 4.2,
    category: "STEM",
    tags: ["science", "genetics", "technology", "thriller"],
    location: { floor: 2, aisle: 1, shelf: "C" },
    available: true,
    digital: false,
    coverId: 12882940,
  },
  {
    id: "st4",
    title: "Prey",
    author: "Michael Crichton",
    summary: "A swarm of self-replicating nanobots escapes from a lab in the Nevada desert, evolving rapidly and becoming a deadly predator. A gripping exploration of nanotechnology and artificial intelligence.",
    rating: 3.5,
    category: "STEM",
    tags: ["science", "technology", "nanotechnology", "ai"],
    location: { floor: 2, aisle: 1, shelf: "D" },
    available: true,
    digital: true,
    coverId: 10984324,
  },
  {
    id: "st5",
    title: "The Wealth of Nations",
    author: "Adam Smith",
    summary: "The foundational text of modern economics explores how free markets, division of labor, and self-interest drive the prosperity of nations.",
    rating: 4.1,
    category: "STEM",
    tags: ["economics", "business", "productivity", "classic"],
    location: { floor: 2, aisle: 2, shelf: "A" },
    available: true,
    digital: true,
    coverId: 12816911,
  },
  {
    id: "st6",
    title: "Frankenstein",
    author: "Mary Shelley",
    summary: "A young scientist creates a living creature from dead tissue, only to face the horrifying consequences of playing God—the original science fiction novel.",
    rating: 4.0,
    category: "STEM",
    tags: ["science", "classic", "ethics", "technology"],
    location: { floor: 2, aisle: 2, shelf: "B" },
    available: false,
    digital: true,
    coverId: 12356249,
  },
  {
    id: "st7",
    title: "The Art of War",
    author: "Sun Tzu",
    summary: "An ancient Chinese military treatise whose lessons on strategy, leadership, and competition remain widely applied in business and everyday life.",
    rating: 4.1,
    category: "STEM",
    tags: ["strategy", "leadership", "business", "classic"],
    location: { floor: 2, aisle: 2, shelf: "C" },
    available: true,
    digital: true,
    coverId: 4849549,
  },
  {
    id: "st8",
    title: "The Lost World",
    author: "Michael Crichton",
    summary: "Years after the disaster at Jurassic Park, a research team ventures to a second island where dinosaurs have been living and evolving in the wild.",
    rating: 4.5,
    category: "STEM",
    tags: ["science", "genetics", "dinosaurs", "adventure"],
    location: { floor: 2, aisle: 2, shelf: "D" },
    available: true,
    digital: false,
    coverId: 10656102,
  },

  // ===== KIDS =====
  {
    id: "k1",
    title: "Rocket Science for Kids",
    author: "Maya Patel",
    summary: "Hands-on experiments and stories that make STEM fun and approachable.",
    rating: 4.3,
    category: "Kids",
    tags: ["kids", "stem", "science", "experiments"],
    location: { floor: 1, aisle: 7, shelf: "D" },
    available: false,
    digital: true,
    coverId: null,
  },
  {
    id: "k2",
    title: "Journey to the Center of the Earth",
    author: "Jules Verne",
    summary: "A professor and his nephew descend into an Icelandic volcano and discover a hidden world of prehistoric creatures, vast oceans, and astonishing wonders deep beneath the surface.",
    rating: 4.1,
    category: "Kids",
    tags: ["kids", "adventure", "science", "classic"],
    location: { floor: 1, aisle: 7, shelf: "A" },
    available: true,
    digital: true,
    coverId: 8359565,
  },
  {
    id: "k3",
    title: "Robin Hood",
    author: "Howard Pyle",
    summary: "The legendary outlaw and his Merry Men steal from the rich and give to the poor in Sherwood Forest, outwitting the Sheriff of Nottingham at every turn.",
    rating: 4.2,
    category: "Kids",
    tags: ["kids", "adventure", "legends", "classic"],
    location: { floor: 1, aisle: 7, shelf: "B" },
    available: true,
    digital: false,
    coverId: 5913135,
  },
  {
    id: "k4",
    title: "The Jungle Book",
    author: "Rudyard Kipling",
    summary: "Young Mowgli is raised by wolves in the Indian jungle, learning the law of the wild from Baloo the bear, Bagheera the panther, and other unforgettable animal characters.",
    rating: 4.1,
    category: "Kids",
    tags: ["kids", "adventure", "animals", "classic"],
    location: { floor: 1, aisle: 7, shelf: "C" },
    available: true,
    digital: true,
    coverId: 3344204,
  },
  {
    id: "k5",
    title: "Just So Stories",
    author: "Rudyard Kipling",
    summary: "A beloved collection of imaginative origin tales explaining how animals got their distinctive features—like how the leopard got his spots and the elephant got his trunk.",
    rating: 3.6,
    category: "Kids",
    tags: ["kids", "animals", "stories", "classic"],
    location: { floor: 1, aisle: 8, shelf: "A" },
    available: true,
    digital: true,
    coverId: 36215,
  },
  {
    id: "k6",
    title: "The Silver Chair",
    author: "C. S. Lewis",
    summary: "Eustace and his schoolmate Jill are sent to Narnia by Aslan on a perilous quest to find a missing prince held captive in an underground kingdom.",
    rating: 4.0,
    category: "Kids",
    tags: ["kids", "fantasy", "adventure", "narnia"],
    location: { floor: 1, aisle: 8, shelf: "B" },
    available: false,
    digital: true,
    coverId: 6950992,
  },
  {
    id: "k7",
    title: "Pippi Longstocking",
    author: "Astrid Lindgren",
    summary: "The strongest girl in the world lives alone with a monkey and a horse, turning everyday life into an endless adventure full of humor and heart.",
    rating: 3.6,
    category: "Kids",
    tags: ["kids", "adventure", "humor", "friendship"],
    location: { floor: 1, aisle: 8, shelf: "C" },
    available: true,
    digital: false,
    coverId: 12391198,
  },
  {
    id: "k8",
    title: "Tom Sawyer, Detective",
    author: "Mark Twain",
    summary: "Tom Sawyer and Huck Finn team up to solve a small-town mystery involving a stolen diamond, mistaken identities, and a murder trial in this playful adventure.",
    rating: 4.2,
    category: "Kids",
    tags: ["kids", "mystery", "adventure", "humor"],
    location: { floor: 1, aisle: 8, shelf: "D" },
    available: true,
    digital: true,
    coverId: 8923621,
  },

  // ===== HISTORY & BIOGRAPHY =====
  {
    id: "h1",
    title: "Narrative of the Life of Frederick Douglass",
    author: "Frederick Douglass",
    summary: "The powerful autobiography of a man who escaped slavery and became one of the most influential abolitionists and orators in American history.",
    rating: 4.3,
    category: "History",
    tags: ["biography", "history", "american", "slavery", "civil rights"],
    location: { floor: 2, aisle: 3, shelf: "A" },
    available: true,
    digital: true,
    coverId: 8247724,
  },
  {
    id: "h2",
    title: "Twelve Years a Slave",
    author: "Solomon Northup",
    summary: "The harrowing true story of a free Black man kidnapped and sold into slavery in the Deep South, who endured twelve years before regaining his freedom.",
    rating: 4.4,
    category: "History",
    tags: ["biography", "history", "slavery", "memoir", "american"],
    location: { floor: 2, aisle: 3, shelf: "B" },
    available: true,
    digital: true,
    coverId: 14856045,
  },
  {
    id: "h3",
    title: "Up from Slavery",
    author: "Booker T. Washington",
    summary: "The inspiring autobiography of an educator born into slavery who founded the Tuskegee Institute and became one of the most prominent African American leaders of his era.",
    rating: 4.3,
    category: "History",
    tags: ["biography", "history", "education", "american", "civil rights"],
    location: { floor: 2, aisle: 3, shelf: "C" },
    available: true,
    digital: false,
    coverId: 119317,
  },
  {
    id: "h4",
    title: "The Life of Olaudah Equiano",
    author: "Olaudah Equiano",
    summary: "One of the earliest autobiographies by an African writer, tracing his journey from capture in West Africa through slavery and eventual freedom in the Atlantic world.",
    rating: 4.0,
    category: "History",
    tags: ["biography", "history", "slavery", "memoir"],
    location: { floor: 2, aisle: 3, shelf: "D" },
    available: false,
    digital: true,
    coverId: 2074044,
  },
  {
    id: "h5",
    title: "Incidents in the Life of a Slave Girl",
    author: "Harriet Jacobs",
    summary: "A groundbreaking account of the unique struggles faced by enslaved women, written by a woman who spent years hiding in a cramped attic to escape her enslaver.",
    rating: 3.9,
    category: "History",
    tags: ["biography", "history", "slavery", "memoir", "women"],
    location: { floor: 2, aisle: 4, shelf: "A" },
    available: true,
    digital: true,
    coverId: 411542,
  },
  {
    id: "h6",
    title: "The Diary of Anne Frank",
    author: "Anne Frank",
    summary: "The diary of a Jewish girl hiding from the Nazis in an Amsterdam attic during World War II—an intimate, heartbreaking, and deeply human document of life under persecution.",
    rating: 4.2,
    category: "History",
    tags: ["biography", "history", "holocaust", "diary", "world war"],
    location: { floor: 2, aisle: 4, shelf: "B" },
    available: true,
    digital: true,
    coverId: 116790,
  },
  {
    id: "h7",
    title: "The Story of Philosophy",
    author: "Will Durant",
    summary: "A lively and accessible tour through the lives and ideas of the world's greatest philosophers, from Plato and Aristotle to Nietzsche and Dewey.",
    rating: 4.2,
    category: "History",
    tags: ["history", "philosophy", "biography", "classic"],
    location: { floor: 2, aisle: 4, shelf: "C" },
    available: true,
    digital: false,
    coverId: 405360,
  },

  // ===== FANTASY & SCI-FI =====
  {
    id: "fs1",
    title: "The Lord of the Rings",
    author: "J. R. R. Tolkien",
    summary: "An epic tale of hobbits, wizards, and the quest to destroy the One Ring before the Dark Lord Sauron can use it to conquer Middle-earth.",
    rating: 4.5,
    category: "Fantasy",
    tags: ["fantasy", "adventure", "epic", "magic", "classic"],
    location: { floor: 3, aisle: 1, shelf: "A" },
    available: true,
    digital: true,
    coverId: 14625765,
  },
  {
    id: "fs2",
    title: "The Hobbit",
    author: "J. R. R. Tolkien",
    summary: "Bilbo Baggins, a comfort-loving hobbit, is swept into an epic quest with a band of dwarves to reclaim their mountain home from the fearsome dragon Smaug.",
    rating: 4.3,
    category: "Fantasy",
    tags: ["fantasy", "adventure", "dragons", "magic", "classic"],
    location: { floor: 3, aisle: 1, shelf: "B" },
    available: true,
    digital: true,
    coverId: 14627509,
  },
  {
    id: "fs3",
    title: "A Game of Thrones",
    author: "George R. R. Martin",
    summary: "Noble families wage war for control of the Iron Throne while an ancient evil awakens beyond the Wall in this sprawling, ruthless epic of power, betrayal, and survival.",
    rating: 4.2,
    category: "Fantasy",
    tags: ["fantasy", "epic", "politics", "dragons", "war"],
    location: { floor: 3, aisle: 1, shelf: "C" },
    available: false,
    digital: true,
    coverId: 9269962,
  },
  {
    id: "fs4",
    title: "The Silmarillion",
    author: "J. R. R. Tolkien",
    summary: "The mythic history of Middle-earth from its creation through the great wars of the Elder Days—the legends behind The Lord of the Rings.",
    rating: 4.0,
    category: "Fantasy",
    tags: ["fantasy", "mythology", "epic", "classic"],
    location: { floor: 3, aisle: 1, shelf: "D" },
    available: true,
    digital: false,
    coverId: 14627042,
  },
  {
    id: "fs5",
    title: "The Scarlet Pimpernel",
    author: "Baroness Orczy",
    summary: "During the French Revolution, a daring English aristocrat leads a secret double life rescuing condemned nobles from the guillotine under a mysterious alter ego.",
    rating: 4.3,
    category: "Fantasy",
    tags: ["adventure", "historical", "classic", "action"],
    location: { floor: 3, aisle: 2, shelf: "A" },
    available: true,
    digital: true,
    coverId: 479102,
  },
  {
    id: "fs6",
    title: "The Man Who Was Thursday",
    author: "G. K. Chesterton",
    summary: "A poet-turned-detective infiltrates a secret council of anarchists, each named after a day of the week, in this mind-bending philosophical thriller.",
    rating: 3.5,
    category: "Fantasy",
    tags: ["fantasy", "philosophical", "mystery", "classic"],
    location: { floor: 3, aisle: 2, shelf: "B" },
    available: true,
    digital: true,
    coverId: 8242857,
  },
  {
    id: "fs7",
    title: "We",
    author: "Yevgeny Zamyatin",
    summary: "In a glass-walled city of the future, a loyal citizen begins to question everything when he falls in love—the dystopian novel that inspired 1984 and Brave New World.",
    rating: 4.0,
    category: "Fantasy",
    tags: ["sci-fi", "dystopia", "classic", "russian"],
    location: { floor: 3, aisle: 2, shelf: "C" },
    available: true,
    digital: false,
    coverId: 5484189,
  },
  {
    id: "fs8",
    title: "Herland",
    author: "Charlotte Perkins Gilman",
    summary: "Three male explorers stumble upon a hidden society composed entirely of women who have built a peaceful, advanced civilization without men.",
    rating: 3.9,
    category: "Fantasy",
    tags: ["sci-fi", "utopia", "feminism", "classic"],
    location: { floor: 3, aisle: 2, shelf: "D" },
    available: true,
    digital: true,
    coverId: 448130,
  },

  // ===== SELF-HELP & WELLNESS =====
  {
    id: "sh1",
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    summary: "The timeless guide to building relationships, communicating effectively, and winning people over—one of the best-selling self-help books of all time.",
    rating: 4.2,
    category: "Self-Help",
    tags: ["self-help", "communication", "leadership", "career"],
    location: { floor: 2, aisle: 5, shelf: "A" },
    available: true,
    digital: true,
    coverId: 13314878,
  },
  {
    id: "sh2",
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    summary: "Based on interviews with over 500 successful people, this classic distills the mindset and habits behind wealth creation into actionable principles.",
    rating: 4.0,
    category: "Self-Help",
    tags: ["self-help", "motivation", "success", "finance"],
    location: { floor: 2, aisle: 5, shelf: "B" },
    available: true,
    digital: true,
    coverId: 14542536,
  },
  {
    id: "sh3",
    title: "The Power of Your Subconscious Mind",
    author: "Joseph Murphy",
    summary: "Unlock the hidden potential of your subconscious mind through visualization, positive thinking, and practical techniques for personal transformation.",
    rating: 3.9,
    category: "Self-Help",
    tags: ["self-help", "psychology", "mindset", "wellness"],
    location: { floor: 2, aisle: 5, shelf: "C" },
    available: false,
    digital: true,
    coverId: 6553019,
  },
  {
    id: "sh4",
    title: "As a Man Thinketh",
    author: "James Allen",
    summary: "A concise, powerful essay on how your thoughts shape your character, circumstances, and destiny—a foundational text of the self-improvement movement.",
    rating: 4.7,
    category: "Self-Help",
    tags: ["self-help", "mindset", "philosophy", "wellness"],
    location: { floor: 2, aisle: 5, shelf: "D" },
    available: true,
    digital: true,
    coverId: 6268048,
  },
  {
    id: "sh5",
    title: "How to Live on 24 Hours a Day",
    author: "Arnold Bennett",
    summary: "A witty and practical guide to making the most of your time, written over a century ago but still surprisingly relevant for anyone feeling overwhelmed.",
    rating: 3.8,
    category: "Self-Help",
    tags: ["self-help", "productivity", "time management", "wellness"],
    location: { floor: 2, aisle: 6, shelf: "A" },
    available: true,
    digital: false,
    coverId: 1760143,
  },

  // ===== PHILOSOPHY & ART =====
  {
    id: "pa1",
    title: "Pensees",
    author: "Blaise Pascal",
    summary: "A brilliant collection of fragmentary thoughts on faith, reason, and the human condition by one of history's greatest mathematical and philosophical minds.",
    rating: 4.0,
    category: "Philosophy",
    tags: ["philosophy", "religion", "classic", "theology"],
    location: { floor: 3, aisle: 3, shelf: "A" },
    available: true,
    digital: true,
    coverId: 6550324,
  },
  {
    id: "pa2",
    title: "Essays",
    author: "Michel de Montaigne",
    summary: "The original personal essays—Montaigne explores everything from friendship and education to cannibals and thumbs, inventing a genre along the way.",
    rating: 3.8,
    category: "Philosophy",
    tags: ["philosophy", "essays", "classic", "french"],
    location: { floor: 3, aisle: 3, shelf: "B" },
    available: true,
    digital: false,
    coverId: 104154,
  },
  {
    id: "pa3",
    title: "On Liberty",
    author: "John Stuart Mill",
    summary: "A passionate defense of individual freedom and free speech that remains one of the most important works of political philosophy ever written.",
    rating: 3.9,
    category: "Philosophy",
    tags: ["philosophy", "politics", "liberty", "classic"],
    location: { floor: 3, aisle: 3, shelf: "C" },
    available: true,
    digital: true,
    coverId: 966821,
  },
  {
    id: "pa4",
    title: "A Vindication of the Rights of Woman",
    author: "Mary Wollstonecraft",
    summary: "A revolutionary argument that women deserve the same education and opportunities as men—one of the founding texts of modern feminism.",
    rating: 3.6,
    category: "Philosophy",
    tags: ["philosophy", "feminism", "politics", "classic"],
    location: { floor: 3, aisle: 3, shelf: "D" },
    available: false,
    digital: true,
    coverId: 675852,
  },
  {
    id: "pa5",
    title: "Picasso: A Biography",
    author: "Patrick O'Brian",
    summary: "A vivid biography of the 20th century's most revolutionary artist, tracing Picasso's life from Barcelona to Paris and his restless reinvention of modern art.",
    rating: 3.9,
    category: "Philosophy",
    tags: ["art", "biography", "modern art", "painting"],
    location: { floor: 3, aisle: 4, shelf: "A" },
    available: true,
    digital: true,
    coverId: 12089,
  },
  {
    id: "pa6",
    title: "Natural History",
    author: "Pliny the Elder",
    summary: "An extraordinary ancient encyclopedia covering art, astronomy, geography, zoology, and botany—the first attempt to catalogue the entire natural world.",
    rating: 3.5,
    category: "Philosophy",
    tags: ["art", "science", "history", "classic", "nature"],
    location: { floor: 3, aisle: 4, shelf: "B" },
    available: true,
    digital: false,
    coverId: 5661503,
  },
];